### ISSUE TITLE
Action is currently broken

### ISSUE THREAD

**Issue by p4vook** [reviewdog/action-misspell#19]
`reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?`
See https://github.com/jjs-dev/jjs/runs/944493356?check_suite_focus=true
Our config for the action:
```
  misspell:
    name: misspell
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          locale: US
```
Yesterday the same action worked fine
