### ISSUE TITLE
PullRequest needs 'git' command: failed to run 'git rev-parse --show-prefix': exit status 128

### ISSUE THREAD

**Issue by miharekar** [reviewdog/action-misspell#42]
I'm getting the following errors
```
Run reviewdog/action-misspell@v1
  with:
    github_token: ***
    locale: US
    level: error
    reporter: github-pr-check
    path: .
    pattern: *
    filter_mode: added
    fail_on_error: false
/usr/bin/docker run --name bcf09c090635f81ea4a0a9e8548b8b74[2](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:2)4e54_a10b8c --label 2bcf09 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_LOCALE -e INPUT_LEVEL -e INPUT_REPORTER -e INPUT_IGNORE -e INPUT_PATH -e INPUT_PATTERN -e INPUT_EXCLUDE -e INPUT_FILTER_MODE -e INPUT_FAIL_ON_ERROR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Advisable/Advisable":"/github/workspace" 2bcf09:c0906[3](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:3)5f81ea[4](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:4)a0a9e8[5](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:5)48b8b[7](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:7)424e54
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 12[8](https://github.com/advisablecom/Advisable/runs/6002454271?check_suite_focus=true#step:4:8)
```

Our yml is fairly standard but just to be certain I tried copying straight from your README example, and I got the error above with this:

```
name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
```
